library(dygraphs)

shinyUI(fluidPage(
        
        titlePanel("Physician Financial Incentives and Cesarean Section Delivery"),
        
        sidebarLayout(
                
                sidebarPanel(
                        
                        selectInput(inputId = "selectState",
                                    label = h4("Select a state to display"),
                                    choices = list("Alabama" = "AL",             
                                                   "Alaska" = "AK",              
                                                   "Arizona" = "AZ",             
                                                   "Arkansas" = "AR",            
                                                   "California" = "CA",          
                                                   "Colorado" = "CO",            
                                                   "Connecticut" = "CT",         
                                                   "Delaware" = "DE",            
                                                   "District of Columbia" = "DC",
                                                   "Florida" = "FL",             
                                                   "Georgia" = "GA",             
                                                   "Guam" = "GU",                
                                                   "Hawaii" = "HI",              
                                                   "Idaho" = "ID",               
                                                   "Illinois" = "IL",            
                                                   "Indiana" = "IN",             
                                                   "Iowa" = "IA",                
                                                   "Kansas" = "KS",              
                                                   "Kentucky" = "KY",            
                                                   "Louisiana" = "LA",           
                                                   "Maine" = "ME",               
                                                   "Maryland" = "MD",            
                                                   "Massachusetts" = "MA",       
                                                   "Michigan" = "MI",            
                                                   "Minnesota" = "MN",           
                                                   "Mississippi" = "MS",         
                                                   "Missouri" = "MO",            
                                                   "Montana" = "MT",             
                                                   "Nebraska" = "NE",            
                                                   "Nevada" = "NV",              
                                                   "New Hampshire" = "NH",       
                                                   "New Jersey" = "NJ",          
                                                   "New Mexico" = "NM",          
                                                   "New York" = "NY",            
                                                   "North Carolina" = "NC",      
                                                   "North Dakota" = "ND",        
                                                   "Ohio" = "OH",                
                                                   "Oklahoma" = "OK",            
                                                   "Oregon" = "OR",              
                                                   "Pennsylvania" = "PA",        
                                                   "Puerto Rico" = "PR",         
                                                   "Rhode Island" = "RI",        
                                                   "South Carolina" = "SC",      
                                                   "South Dakota" = "SD",        
                                                   "Tennessee" = "TN",           
                                                   "Texas" = "TX",               
                                                   "Utah" = "UT",                
                                                   "Vermont" = "VT",             
                                                   "Virgin Islands" = "VI",      
                                                   "Virginia" = "VA",            
                                                   "Washington" = "WA",          
                                                   "West Virginia" = "WV",       
                                                   "Wisconsin" = "WI",           
                                                   "Wyoming" = "WY"),
                                    selected = "AR"),
                        
                        selectInput(inputId = "selectCPT", 
                                    label = h4("Select more CPT code to display"), 
                                    choices = list("CPT 59400" = 59400,
                                                   "CPT 59409" = 59409,
                                                   "CPT 59410" = 59410,
                                                   "CPT 59510" = 59510,
                                                   "CPT 59514" = 59514,
                                                   "CPT 59515" = 59515,
                                                   "CPT 59610" = 59610,
                                                   "CPT 59612" = 59612,
                                                   "CPT 59614" = 59614,
                                                   "CPT 59618" = 59618,
                                                   "CPT 59620" = 59620,
                                                   "CPT 59622" = 59622), 
                                    selected = 59400,
                                    multiple = TRUE),
                        
                        helpText("Note: You can also type and search in the options.")
                ),
                
                mainPanel(dygraphOutput("dygraph"),
                          br(),
                          em("Note: Use the range selector to expand or narrow the time series."))
        )
))